cp ../all_exams/all_exams.pdf ../docs/all_exams
cp ../labs/primer.pdf ../docs/labs
cp ../labs/all_labs.pdf ../docs/labs
cp ../lab_sols/lab_sols*.mw ../docs/lab_sols
cp ../lab_sols/pdf/lab_sols*.pdf ../docs/lab_sols/pdf
cp ../lab_sols_maxima/*.wxmx ../docs/lab_sols_maxima
cp ../lab_setup/defineq.mw ../docs/lab_setup
cp ../lab_setup/ratint.mw ../docs/lab_setup
cp ../lectures/all_handouts.pdf ../docs/lectures
cp ../lectures/all_lectures.pdf ../docs/lectures
cp ../presentations/presentation*.mw ../docs/presentations
cp ../presentations/presentation*.pdf ../docs/presentations
cp ../tutorials/all_probs.pdf ../docs/tutorials
